### ISSUE TITLE
The dependency on kodi.binary.instance.pvr version 5.8.0 could not be satisfied.

### ISSUE THREAD

**Issue by dazedcrazy** [CoreELEC/CoreELEC#21]
Just built from master and can't install pvr.mediaportal.tvserver from the CoreElec repo

**Comment by Raybuntu** [comment]
All Addons were recently compiled against the same Kodi version we released. Either you are using an older version of the add-on or you had it cached.
Manually check for updates. Remove zips from addons packages cache and reinstall from our repo.

**Comment by dazedcrazy** [comment]
Tried that, removed all traces of it and still won't install
[kodi.log](https://github.com/CoreELEC/CoreELEC/files/1929417/kodi.log)
```
19:55:28.059 T:4099649552   DEBUG: CAddonInstaller: installing 'pvr.mediaportal.tvserver' version '3.4.3.2' from repository 'repository.coreelec'
19:55:28.069 T:3892310848   DEBUG: CAddonInstallJob[pvr.mediaportal.tvserver]: requires kodi.binary.instance.pvr version 5.8.0 which is not available
19:55:28.070 T:3892310848   ERROR: CAddonInstallJob[pvr.mediaportal.tvserver]: The dependency on kodi.binary.instance.pvr version 5.8.0 could not be satisfied.
19:55:28.100 T:4099649552   DEBUG: CGUIMediaWindow::GetDirectory (addons://repository.coreelec/xbmc.pvrclient)
19:55:28.100 T:4099649552   DEBUG:   ParentPath = [addons://repository.coreelec/xbmc.pvrclient]
```

**Comment by Raybuntu** [comment]
But you are using 8.90.0 right?

**Comment by dazedcrazy** [comment]
I built myself from here, so from this commit https://github.com/CoreELEC/CoreELEC/tree/726130575d47bc6a3b75fe7f2c17575749c9e5cc

**Comment by Raybuntu** [comment]
Then you have to rebuild all addons yourself. We can't upgrade those otherwise it will break for all others. We will once 8.90.1 is out.

**Comment by dazedcrazy** [comment]
Ah cool I'll do that, thanks

**Comment by rafacouto** [comment]
@Raybuntu Any create_all_addons script?

**Comment by adamg88** [comment]
We use repo-tool for that @rafacouto
